### ISSUE TITLE
地図の技術選定

### ISSUE THREAD

**Issue by kenta-wakasa** [flutteruniv/joyato#2]
地図機能のためにどのパッケージを使用するべきかを調査してください。
夜の街にぽっと灯りがともっているような画を想像しています。そういうエモい雰囲気が出せるものだと望ましいです。

# 成果物
- 2つ以上のパッケージを比較しその両方がためせるサンプルアプリを自身のGitHub上で公開すること
- それらの比較について zenn で記事にまとめること

# 比較する評価項目

- 現在地を表示できるか
- 現在地の表示アイコンを変更できるか
- 現在向いている方角を表示できるか
- 任意の場所にピンを立てることができるか
- ピンのアイコンは変更可能か
- ピンの大きさは変更可能か
- 地図そのものの見た目を柔軟に変更できるか
  - 夜の雰囲気を出せる色合いに変更可能か
  - 地形などの表示内容をデフォルメ可能か
  - 地形情報などをできるだけ削ぎ落とした白地図のような形にできるか
- 料金がどのくらいかかるか
  -  ピンを立てることや地図利用そのものに料金は発生するか
- パッケージのAPIは使いやすいか

**Comment by samuraituru** [comment]
「google_maps_flutter」と「flutter_map」パッケージでのサンプルアプリを作成し自身のGitHub上で公開完了
https://github.com/samuraituru/sample_google_maps_flutter.git
https://github.com/samuraituru/sample_flutter_map.git

Zennにて執筆完了
https://zenn.dev/odaken/articles/615f12930c7f5d
