### ISSUE TITLE
HomePageにGoogleMapを表示する

### ISSUE THREAD

**Issue by kenta-wakasa** [flutteruniv/joyato#22]
いまHomePageにはサインアウトのためのボタンが中央に配置されているだけになっている。
そのHomePageを修正し、画面全体にGoogleMapが表示されるようにしてほしい。

もともとあったサインアウトボタンは削除する。
かわりにAppBarを新規で追加した上でその中のactionsプロパティになんらかのボタンを配置し、そこでサインアウトできるようにすること。

**Comment by samuraituru** [comment]
最小構成版でPull Requestを出しました。
マージ後、再度API-KEYを外部からインポートするスプリクトなどを実装したいと思っています。

**Comment by samuraituru** [comment]
Pull Requestを出しました。
また、API-KEY設定も実装しました！
